version: '3.8'

services:
  app:
    build: .
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --port 5174 --host
    environment:
      NODE_ENV: development
